config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :photos
  devise_for :users
  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Photo, user_id: user.id
    can :read, Photo
    can :manage, Comment, user_id: user.id
    can :read, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates_presence_of :user_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_photo, only: [:create, :update]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new(photo_id: params[:photo_id])
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to photo_path(@photo), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to photo_path(@photo), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_photo
      @photo = Photo.find(comment_params[:photo_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:photo_id, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @comments ||= @photo.comments
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    authorize! :manage, @photo
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    authorize! :manage, @photo
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_form.html.slim
= form_for @comment do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .field
    = f.hidden_field :photo_id
  .field
    = f.label :content
    = f.text_area :content
  .actions = f.submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

= link_to 'Show', @comment, class: 'btn btn-default'
= link_to 'Back', comments_path, class: 'btn btn-default'

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th Photo
      th User
      th Content
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.photo_id
        td = comment.user_id
        td = comment.content
        - if can? :manage, comment
          td = link_to 'Show', comment, class: 'btn btn-default'
          td = link_to 'Edit', edit_comment_path(comment), class: 'btn btn-warning'
          td = link_to 'Destroy', comment, data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path, class: 'btn btn-default'

app/views/comments/show.html.slim
p#notice = notice

p
  strong Photo:
  = @comment.photo_id
p
  strong User:
  = @comment.user_id
p
  strong Content:
  = @comment.content
- if can? :manage, photo
  = link_to 'Edit', edit_comment_path(@comment), class: 'btn btn-warning'
= link_to 'Back', comments_path, class: 'btn btn-default'

app/views/home/index.html.slim
.welcome-contents
  h1 Welcome to my page
  br
  = link_to 'See Photos', photos_path, class: 'btn btn-default'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookpad</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <%= yield %>
    <div id="footer">@Nguyen Xuan Khoai</div>
  </body>
</html>

app/views/photos/_form.html.slim
= form_for(photo) do |f|
  - if photo.errors.any?
    #error_explanation
      h2
        = pluralize(photo.errors.count, "error")
        |  prohibited this photo from being saved:
      ul
        - photo.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit

app/views/photos/edit.html.slim
.edit-photo
  h1
    | Editing Photo
  = render 'form', photo: @photo
  = link_to 'Show', @photo, class: 'btn btn-info'
  = link_to 'Back', photos_path, class: 'btn btn-default'

app/views/photos/index.html.slim
.photo-contents
  p#notice
    = notice
  h1
    | Photos
  .btn-new-photo
    = link_to 'New Photo', new_photo_path, class: 'btn btn-green'
  br
  - @photos.each do |photo|
    .col-sm-04.photo-element
      = link_to image_tag(photo.image.url(:medium)), photo
      br
      = link_to 'https://www.facebook.com/sharer/sharer.php?u=' + URI.join(request.base_url, photo.image.url).to_s, class: 'btn btn-blue', target: '_blank' do
        i.fa.fa-facebook-official
      h5 Owner: #{ photo.user.email }

      = link_to 'Show', photo, class: 'btn btn-info'
      - if can? :manage, photo
        = link_to 'Edit', edit_photo_path(photo), class: 'btn btn-warning'
        = link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

app/views/photos/new.html.slim
.new-photo
  h1
    | New Photo
  = render 'form', photo: @photo
  = link_to 'Back', photos_path, class: 'btn btn-default'

app/views/photos/show.html.slim
p#notice
  = notice
.photo-detail
  = image_tag @photo.image.url
  br
  h3 Comments:
  .comment-contents
    - @comments.each do |comment|
      p
        strong #{ comment.user.email }:&nbsp
        | #{ comment.content }
      - if can? :manage, comment
        = link_to 'Edit', edit_comment_path(comment), class: 'btn btn-warning'
        = link_to 'Delete', comment_path(comment), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn btn-danger'
  br
  = link_to 'Share on Facebook', 'https://www.facebook.com/sharer/sharer.php?u=' + URI.join(request.base_url, @photo.image.url).to_s, class: 'btn btn-blue', target: '_blank'
  = link_to 'Add comment', new_comment_path(photo_id: @photo.id), class: 'btn btn-success'
  br
  - if can? :manage, @photo
    = link_to 'Edit', edit_photo_path(@photo), class: 'btn btn-warning'
  - else
    p
    strong
      | Owner: &nbsp
    = @photo.user.email
    br
  = link_to 'Back', photos_path, class: 'btn btn-default'

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br